### PR TITLE
Email applicant when their application is approved (haven't paid yet)

### PR DESCRIPTION
**Pull request by weedySeaDragon**
PT Story:  https://www.pivotaltracker.com/story/show/133951685

(most of the code had already been written.  It just wasn't being called yet.)

### Changes proposed in this pull request:
1. Add the small method in MembershipApplicationMailer to create the mail (code already existed)
2. Create the .html and .text views of the email (code already existed)
3.   in the MembershipApplication `accept_membership` method, put in the 1 line of code needed to send the email to the applicant

### Screenshots (Optional):

_Note that in the emails below where it says `localhost` it will have the actual deployed system address instead._

**text format:**
shf-applicant-app-approved-text-2

**html format**
shf-applicant-app-approved-html-2

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Comment by thesuss** [comment]
It's perfect in many aspects, but not quite right anymore though?
This should be sent when they have paid, and this one should be replaced with info on how to pay?

**Comment by weedySeaDragon** [comment]
@thesuss Yes, you're exactly right. :-)  

So: do we need to change the wording on this?

**Comment by thesuss** [comment]
@weedySeaDragon  The wording is perfect. But not for this event. Its perfect for when the membership fee has been paid. It needs to be completely exchanged. Will have to look into it deeper. Can do tomorrow before the meeting I hope.

**Comment by weedySeaDragon** [comment]
@thesuss I changed the mail views to just have some placeholder text for this.

(I moved the previous views into the directory for `UserMailer` so that they are there if/when we ant to use them when a user becomes a member -- after they have paid.)

**Comment by thesuss** [comment]
New text: 

Hej
Din ansökan har nu blivit godkänd. Det som är kvar innan du är medlem i systemet är att betala din medlemsavgift. Det gör du via [Link to where to pay membership fee].  
 **if H-branding is not paid** 
  _När detta är gjort behöver du göra färdigt din företagssida och betala din H-märkningsvagift. Mer information om hur du gör det kommer i ett mail efter att du betalt din medlemsavgift._ (italics to illustrate it only needs to come if H-branding is not paid ) 

Tack för att du vill vara medlem och bidrar till ett kvalitetssäkrat hundsverige.

Signature   
____ 

In english: 

Hello
Your application is now approved. What is left before you are registered as a member in the system is to pay your membership fee. You do this via [Link to where to pay membership fee].  
 **if H-branding is not paid** 
  _When this is done you will need to complete your business-page and pay your H-brandung fee. More information about this will come in an e-mail after the membership-fee is registered as paid._  (italics to illustrate it only needs to come if H-branding is not paid ) 

Thank you for wanting to be a member and contributing to a quality assured dog-Sweden. 
(feel free to rephrase) 

Signature

**Comment by thesuss** [comment]
subject: 
Din ansökan till Sveriges Hundföretagare är godkänd. 

Your application to Sveriges Hundföretagare is approved.

**Review by RobertCram — APPROVED** [review]

**Review by patmbolger — APPROVED** [review]

**Comment by weedySeaDragon** [comment]
@thesuss - I updated the text per your feedback.  The screenshots show the new text.
Merge if you're ok with it.

**Pull request merged**
