### PR TITLE
Gives some Love to Company Show page

### PR DESCRIPTION
**Pull request by thesuss**
As User
image
. 
. 
. 
. 
As Admin
image
. 
. 
. 
. 
As Admin Responsive:
image

. 
. 
. 
. 
Detail:
image

### CODE REVIEW

**Comment by thesuss** [comment]
No violations found. Woof! 🎉

**Comment by patmbolger** [comment]
As an admin, I entered a note in the h-brand edit modal (3 paragraphs).   This happened:

Screen Shot 2019-04-01 at 9 34 27 AM

**Review by patmbolger — CHANGES_REQUESTED** [review]
See comment.

**Comment by patmbolger** [comment]
Otherwise I really like the changes.

**Comment by weedySeaDragon** [comment]
what @patmbolger  - the changes look good!  (once the note thing is fixed, I think it's good to go)

**Pull request merged**
