### PR TITLE
update diagrams for  company addresses

### PR DESCRIPTION
**Pull request by weedySeaDragon**
## PT Story: Company should have two addresses - only one is currently represented
https://www.pivotaltracker.com/story/show/146585599
Updating documentation as we are discussing and working through the story.

### Changes proposed in this pull request:
1. moved the .png files under /docs/wiki since they're used for the wiki _(Thanks for leading the way, Pat!)_
2. default addresses diagram:  propose that a **Company** has:
    - a mailing address
    - a billing address (default = the mailing address)
    - 1..many locations (default = 1 location, it's default = the mailing address)
3. updated text in the _Addresses Required_ document (.png)
4. needed to break up the graphics into another .png because of layout stuff

Ready for review:
 @AgileVentures/shf-project-team

### CODE REVIEW

**Comment by patmbolger** [comment]
1. I think this comment (in company mailing address block) might be better in the member mailing address block:

screen shot 2017-09-15 at 4 10 38 pm

2. I think we decided that the mailing address == the default location address.  So, perhaps this comment:

screen shot 2017-09-15 at 4 10 48 pm

would be better as "This is also the default location address."  Or just drop it altogether, since the diagram clearly indicates the company mailing address as the default location address.

**Review by patmbolger — APPROVED** [review]

**Comment by weedySeaDragon** [comment]
Thoughts @RobertCram ?  @thesuss ?

**Comment by RobertCram** [comment]
Looks good Ashley. 

As a follow-up to think about: in my experience it is not trivial to get these things right (and understandable) for the user (especially with default addresses). We have to think hard about copying or referencing the default addresses. e.g. what happens (or rather what should happen) when  a default is used, and changed later?

**Review by RobertCram — APPROVED** [review]

**Comment by patmbolger** [comment]
Looking at this further, and also reflecting on Robert's comments re default relationships, I am thinking that we could simplify the addresses model, make the address structure clearer to the user, remove the idea of default addresses, and also make it much easier to implement.

Speaking first to a company model, the central idea is that a company can have multiple addresses.  Those addresses have the same attributes as the current single address, including `visibility_level`.  In addition, we now add to the Address model the attributes: `mailing_address` and `billing_address` (both booleans).

This simple model allows the user to create multiple addresses, and set one as the mailing address.   The same holds for billing address.

This also allows the user to designate any combination of attributes for an address - for instance, a single address (which might suffice for many (most?) companies, can be marked as 1) my mailing address, 2) also my billing address, and 3) also my place of business, although I will set my address (map) visibility to city level as I don't want to disclose my street address to the world.

If we end up adding more company-specific attributes to a company address, then we could subclass Address to CompanyAddress. At this point, there is no need for that.

The same business rules apply: only one mailing address, and only one billing address. However, each of those can also be "location" addresses.

Now, we get away from the difficulties of managing default address relationships, and everything is very clear and explicit to the user.

This same concept works _exactly_ the same for a member, with the exception that address visibility is not an attribute used for the user model (although this could change, I suppose).

So, the distinctions we need to manage (company vs member, billing?, mailing?) are managed via attributes added to the polymorphic Address model.  (this also means that attribute `address_visibility` moves from the Company model to the Address model).

**Review by patmbolger — COMMENTED** [review]
Please see my new comments.

**Comment by thesuss** [comment]
@patmbolger  I like that idea, I just want to know what happens if a user needs a different address? Like For me all three are the same, but for another person they are different, so she ticks yes for mailing and billing, but needs a different for location, how will that be done?

**Comment by patmbolger** [comment]
@thesuss - in that case, the user would create two company addresses.

Address 1 is marked as mailing _and_ billing, and the address visibility is set to _none_, since this address should not show up on a map.

Address 2 is the location address, visibility can be set at desired level, and, if not _none_, that address shows up on the map.

**Comment by RobertCram** [comment]
@patmbolger Very creative idea. Never seen such a scheme used before, but it sounds like a great setup. It moves the complexity away from the user, and probably (having the experience that complexity rather moves than disappears) towards the developers. Looking forward to that.

**Review by thesuss — APPROVED** [review]

**Comment by thesuss** [comment]
If Kicki has time on monday we could ask her about addresses too, as she is also one with several. If needed more input, that is.

**Comment by thesuss** [comment]
Anything more needed to do in this one? What are the remaning Qs?

**Comment by patmbolger** [comment]
I think we could update the diagrams to reflect where we are at this point - which is that we have a much simpler Address scheme than originally envisioned in this diagram.  That is:

1. Users (or members) currently do _not_ have addresses.

2. We don't appear to need billing addresses for companies or users, as we are adopting online payments for everything.

We can adapt the design of we expand the address model later.

**Comment by thesuss** [comment]
Cool. Good to know what's to do. If I could I would. =)

**Comment by weedySeaDragon** [comment]
added image to the wiki page that shows the current implementation

**Pull request merged**
