### PR TITLE
Fixes problem with hiding titles and missing flashes

### PR DESCRIPTION
**Pull request by thesuss**
PT Story: https://www.pivotaltracker.com/story/show/138063103

Changes proposed in this pull request:
1. moved around the lines in _top partial

I see the default state has changed in the schema, I did not change this.... ? 

Screenshots (Optional):
skarmavbild 2017-01-24 kl 14 13 23

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
Re: the schema change (default state is now new) happened in a commit in PR #115 [here's the migration file where it was done](https://github.com/AgileVentures/shf-project/commit/9747766797a7c5110428c455a99640b7073a44d2#diff-53b9554e54c479d7a55ca7c743a61717)

This probably is showing up because of a merge or rebase you did on the develop branch.
I happened to know when and where this change happened, but you can also use 'blame' and 'history' to help figure this kind of thing out. (easy way = use the buttons in Github at the top of files)

**Review by weedySeaDragon — CHANGES_REQUESTED** [review]
Need a feature test for this: ensuring that the flash messages show.

(I'm happy to help you with steps if needed.)

**Comment by patmbolger** [comment]
When I a view the companies index page (not logged in) I see this:

screen shot 2017-01-24 at 3 42 50 pm

The "FIND H-LABELED COMPANIES" is not seen unless I pull the page down with my mouse - then I can see that but once I lift my finger the text recedes upward and disappears again.

**Comment by thesuss** [comment]
@patmbolger I can not replicate in any browser...

**Comment by thesuss** [comment]
@weedySeaDragon Cucumber can see them already.

**Comment by thesuss** [comment]
@weedySeaDragon re schema. Then the develop schema was not updated when the change occurred. It's fine anyway then :)

**Comment by patmbolger** [comment]
@thesuss - I see them now.  Not sure what happened as nothing changed (?).

**Review by patmbolger — APPROVED** [review]

**Comment by weedySeaDragon** [comment]
Re: testing --
We should have a test that will ensure that we don't have this problem again.  (Whenever a bug is found, that's a sign that you have a hole in your testing:  the bug got through because there wasn't a test to check for it/catch it.)

I'm not entirely sure how to test this.  We can all talk about this and figure it out.

**Comment by thesuss** [comment]
@weedySeaDragon Normally I'd agree, this time it's due to the legacy code of the template. Had we built it the problem would not have occurred. Had I (being familiar with the legacy code) done the removal of the logo the problem would not have occurred. 

I think this will also take care of some of the issues, eventually.
https://www.pivotaltracker.com/story/show/134212887

**Comment by weedySeaDragon** [comment]
@thesuss  I think we could still write a test for this so that we don't run into this again.  (Can't guarantee who will make the next change. And in some ways, it's even more important to write tests for legacy code since it's much more of an unknown and likely to be fragile when changes are made.) 
But I also think at this point it's time to move on with this one.  We can keep discussing this ('found a bug, write a test...') in our meetings, chats, etc.
Thanks for pointing out the task in PT (https://www.pivotaltracker.com/story/show/134212887).  That will be good. (and also kind of a bear, I imagine!)

**Review by weedySeaDragon — APPROVED** [review]

**Pull request merged**
