### PR TITLE
[HOTFIX] Delete company payments if company deleted

### PR DESCRIPTION
**Pull request by patmbolger**
PT Story: https://www.pivotaltracker.com/story/show/154004514

Changes proposed in this pull request:
1. Company model destroys payments if company is destroyed
2. Add steps to cucumber test that fail without this change

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Review by weedySeaDragon — CHANGES_REQUESTED** [review]
In the test(s), are we verifying that the payments are actually deleted?

I'm not seeing it.  (maybe I just need a pointer to them)

**Comment by patmbolger** [comment]
@weedySeaDragon - you're right - they're missing. Added a unit test to Company.

**Review by weedySeaDragon — APPROVED** [review]

**Review by RobertCram — APPROVED** [review]
I didn't realise you could do a "dependent: :destroy". For another chore: I guess that would also apply for the uploaded_files belonging to an shf_application?

**Comment by patmbolger** [comment]
@RobertCram - Yes, I would think it would.

**Pull request merged**
