### PR TITLE
Use time-zone aware methods everywhere: `Date.current`  `Time.zone.___` etc

### PR DESCRIPTION
**Pull request by weedySeaDragon**
### PT Story:  User spec fails because Date.today != Date.current 
https://www.pivotaltracker.com/story/show/152993897

If your timezone is set and you run the spec at a time where UTC is a different day (ex: it is 10pm for you, but already into the next day in UTC), then the spec failed because the spec is looking at UTC (tomorrow) but the model returns a date and time for your timezone (today).

This goes beyond just the User model and user helper methods, but I thought that the changes weren't that complicated, _and_ doing them all in this PR leaves all the code in a consistent state.  (Every Time or Date related method has now been updated.)

I wrote a comment explaining why we should use `Date.current` et al in `app/helpers/users_helper.rb` and `app/models/users.rb` (it's the same comment).

### Changes proposed in this pull request:
1.  Changed all Date and Time methods so that they use the "time zone aware" methods, like `Date.current` and `Time.zone.___`:
   The changes touched on these:
   - **User model, user helper methods** and related specs and features
   - **Payment model, _including the migration_**  `20171026103648_add_dates_to_payments.rb`
   - Admin export: the Time method for the timestamp in the export filename 
   - ActivityLogger: the start time method
   - Mail errors: the Time method for the timestamp in the error message 

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Comment by RobertCram** [comment]
Doesn't this mean `Date.today` should be replaced by `Date.current` everywhere in the code, and not just in this spec?

**Comment by patmbolger** [comment]
I think it's the reverse - we have to replace `Date.current` in the code with `Date.today`.

For purposes of payment tracking, we need a consistent starting point for "today", and `Date.today` will return the day based on system time on the hosting server.

**Comment by RobertCram** [comment]
Time and timezones always get me confused. As long as we're consistent, I'm good :)

You and me both!

**Comment by weedySeaDragon** [comment]
This is good -- it's made me think through the UX (user interactions) more deeply.

- The system (production server) is storing all dates according to UTC, so
- All date calculations should be done using **Date.today**  (which uses UTC)

Note that this prompted me to create a new story in PT:  **[Display dates/times in the user's local time zone](https://www.pivotaltracker.com/story/show/153071166)**

**Comment by patmbolger** [comment]
Yes, we have to think about how to display times to the user in their time zone.  

I think this is a small enough thing that we can attack it in another story as needed.

Also, the membership duration is not based on time or day of payment, but rather is set too start the day after the prior payment's expiration date.  The tooltip for the payment button says that to the user (in so many words).

**Review by thesuss — APPROVED** [review]

**Comment by patmbolger** [comment]
After thinking about this more (and wrestling with using `Timecop` for testing) I think that @RobertCram is right about using `Date.current` (vs. `Date.today`) for dates that have to correspond to the user's date.   Dates having to do with timestamps of DB data (as an example) are a different animal altogether.

**Comment by weedySeaDragon** [comment]
So after thinking about this _more_  (and hours later than the rest of you ;-) ), and hitting up the interwebs, I have more thoughts.

This write up is what finally put it all together for me:

**[The Exhaustive Guide to Rails Time Zones _or What is the difference between Time.zone.now and Time.now_](http://danilenko.org/2012/7/6/rails_timezones/)**

The explanation is excellent:  simple, straightforward examples that explain the different classes and how things can end up wacky. It's not a very long read; I really recommend it.

I agree with you 2, @RobertCram  and @patmbolger -- **we should use `Time.current`** 

We really should be using `Time.zone._____`  instead of just `Time._____`.

Ex:
  We should use this:  **`Time.zone.now`**       instead of this:  `Time.now`
  We should use this:  **`Time.zone.today`**   instead of this: `Time.today`

**`Date.current`** is == `Time.zone.today` (for our purposes)  so:

  We should use this:  **`Date.current`**    instead of this: `Date.today`

 (You can see the tiny method that defines Date.current in the ActiveSupport gem: activesupport-5.1.0/lib/active_support/core_ext/date/calculations.rb)


Also, using `Time.zone._____` will make it easy to move forward and display things in CET easily. (And easy, too, to perhaps allow individual users to set their own time zone in the future).


TMI/tldr:  I currently think that it is good to leave our Rails Application time zone as UTC (the default).  I need to think more deeply about this at some other time (ha!).  I think that testing is the potential trouble spot, and we can address it by using the right strategies/classes/methods in our tests.

**Comment by weedySeaDragon** [comment]
@AgileVentures/shf-project-team :   I updated _all_ `Date` and `Time` methods to use "time-zone aware" methods.  Ready for review again.

This goes beyond just the User model and user helper methods, but I thought that the changes weren't that complicated, _and_ doing them all in this PR leaves all the code in a consistent state.  (Every Time or Date related method has now been updated.)

I wrote a comment explaining why we should use `Date.current` et al in `app/helpers/users_helper.rb` and `app/models/users.rb` (it's the same comment).

**Comment by patmbolger** [comment]
Good research @weedySeaDragon .... I updated my existing PR with one more required change (`Date.new(...).in_time_zone`).

**Comment by RobertCram** [comment]
Thanks for researching this Ashley. I myself would prefer to use the `Date.zone.___` and `Time.zone.___` everywhere because it draws explicit attention to the code being aware of the time zone, and it keeps everything similar.

So e.g. 

`Date.zone.today` instead of `Date.current`
`Date.zone.local(2018, 12, 31)` instead of `Date.new(2018, 12, 31).in_time_zone`

But of course I have no problem with leaving this as is.

**Review by RobertCram — APPROVED** [review]

**Comment by weedySeaDragon** [comment]
@RobertCram I agree - making it explicit is better.  But I'm also ok if someone wants to slide in using `Date.current` (ahem, @patmbolger ;-) ). 

  I'll make changes _and_ I'll include your comment in the doc in our wiki so that folks can keep that in mind as well.

**Comment by weedySeaDragon** [comment]
@RobertCram I didn't change any code.  But I did add a comment to the wiki page https://github.com/AgileVentures/shf-project/wiki/Dates-and-Times-and-Timezones-(oh-my!)

**Pull request merged**
