### PR TITLE
Improve Membership App file upload UX so users don't skip uploading files

### PR DESCRIPTION
**Pull request by weedySeaDragon**
PT Story: Need to improve file-upload visibility
https://www.pivotaltracker.com/story/show/141029197

This is a first attempt at improving the user experience (UX) when a user fills out a membership application.  Users are skipping over the section to upload files.

**This is closed because PR #192 takes its place.** (The commits for this PR had gotten too messy.  Used `merge` when I really should have used `rebase`)

**Translations needed!**

### Changes proposed in this pull request:
1.  Add instructions so users understand the importance of uploading files. Let users know they'll have 3 sections to complete.
2.  Set off each of the 3 major sections so users can see each of them clearly. (Indent the text under each section header to help set them off.)
3. If a users selects more than 1 file to upload, show the list of the files that will be uploaded when they submit the page.
3. Use background color and styling per @thesuss example in PivT to highlight the file upload section even more
4. If no files have been uploaded, show the warning icon
5. Added CSS classes and ids to views so styles can be applied

## Ready for Review
@patmbolger @thesuss 

### If no files have been uploaded:

**New/edit view:**

new-app-nofiles-warning-sv

---

### Applicant has chosen 3 files but hasn't saved their new application yet:

new-app-nofiles-warning-3-to-update-sv

### Editing an application with files already uploaded:

edit-app-with-2files-sv

---

(English):

edit-app-with-2files-en

---

### Viewing an application

show-application-sv

Ready for review:

### CODE REVIEW

**Comment by patmbolger** [comment]
1) Do we have a list of files that need to be uploaded (which vary, possibly, by type of services offered)?  If so, perhaps we could have a link ("Required Documents") that would list those for the user - perhaps a modal bootstrap dialog.

2) Can we make the "no files uploaded" message a bit more obvious?  Perhaps a bigger font, in red, whatever?

**Comment by thesuss** [comment]
My comment: Very nice!

**Comment by weedySeaDragon** [comment]
@patmbolger We don't have a list of 'required' files (AFAIK).  

We definitely can make the 'no files uploaded' message bigger or redder or whatever (it's just changing the CSS).  I'll do both so we can see.

**Comment by thesuss** [comment]
Why is the "sanitie website" stuff here? Is that a part of this PR? 
(just wonders why there are 36 files changed because of styling of one form... ) 
@weedySeaDragon @patmbolger

**Comment by weedySeaDragon** [comment]
Good point, @thesuss .  It's definitely my rebasing/merging stuff. :-)
I can clean it up after we know that this looks like we want it (at least for this iteration).

The *important thing* I need to know so that hopefully we can demo this to Ulrike tomorrow. (Then we can worry about getting this commit cleaned up secondarily.)

**Comment by thesuss** [comment]
I think it looks good

**Review by patmbolger — APPROVED** [review]
This looks really good.  Very clear and hard to miss.

**Comment by weedySeaDragon** [comment]
I'll figure out a way to clean up the commits.  (Again with the "rebasing/merging" stuff.  ARGH!)
Thanks to you both for the feedback on how this looks.

**Pull request closed without merging**
