### PR TITLE
CSV export: reorder, membership numbers,  utf8 chars not showing up in windows

### PR DESCRIPTION
**Pull request by weedySeaDragon**
PT Story:  Mailchimp csv take 2
https://www.pivotaltracker.com/story/show/140629843

@thesuss :  I think the encoding problem is with Windows.  The characters appear correct on my Mac.  I have now explicitly saved the file as UTF-8, but I'm not sure that will be sufficient to make it work on a Windows machine. (My windows machine isn't set up to test this easily right now.)
Can you check to see if this change fixes it on your end?  

**Changes proposed in this pull request:**
1.  reordered columns so email is first
2. added membership number column (before status)
3. explicitly set the string (which is the downloaded 'csv file') as UTF-8

**Screenshots**
screen shot 2017-03-01 at 11 56 58 am

Ready for review:
@thesuss

### CODE REVIEW

**Review by thesuss — APPROVED** [review]

**Comment by thesuss** [comment]
@patmbolger Any comments?

**Comment by thesuss** [comment]
Ack :(  this pr now has changes it should not have and changes files it should not change... @weedySeaDragon ?

**Comment by patmbolger** [comment]
Definitely has changes associated with other PR's.

Does rebasing help?

**Comment by weedySeaDragon** [comment]
Closing because I've gotten this branch too tangled up with rebases and merges and commits (oh my!).

Will open a new PR so that the commits are clean.

**Pull request closed without merging**
