### PR TITLE
CHORE upgrade to ruby 2.7.6

### PR DESCRIPTION
**Pull request by weedySeaDragon**
#### PT URL: https://www.pivotaltracker.com/story/show/177966458

Changes needed are pretty small

Will need to make changes to the Semaphore workflow to test this (change the version of ruby used)

## Changes proposed in this pull request:
1.  change some range expectations
2.  fix splat usage (don't convert Hash to Array, etc.)
3. fix "too many files open" for cucumber (known problem when upgrading to 2.7

## Ready for review:
@patmbolger @RobertCram

### CODE REVIEW

**Review by RobertCram — APPROVED** [review]
Still trying to get it to work on arm, but no problem to merge this now.

**Review by RobertCram — CHANGES_REQUESTED** [review]
The problem (this time) wasn't Nokogiri, but the platforms section In the Gemfile.lock. The ruby and linux platforms have been removed.

Can you please restore them (_bundle lock --add-platform ruby x86_64-linux_), and commit the new Gemfile.lock?

**Comment by weedySeaDragon** [comment]
Oops - my bad.  Sorry!

**Comment by weedySeaDragon** [comment]
@RobertCram Should we be specifying the version of `x86_64-darwin` ? I'm running 20.6.0  (`uname -r`) but I'm sure yours is different and others may be different yet.

I find the way Bundler handles platforms with `bundle lock add-platform` frustrating.  I feel that specification should be part of the Gemfile, not added with an external command.  <sigh>

**Pull request merged**
