### PR TITLE
Implement Design 

### PR DESCRIPTION
**Pull request by thesuss**
Piv:
https://www.pivotaltracker.com/story/show/133168711

Changes: 
- Adds bootstrap, font-awesome and the template css. 
- Adds an index page with root so to view the design
- Adds partials for design elements
- Some JS to expand the menu on mobile
- Using Font awesome helpers: https://github.com/FortAwesome/font-awesome-sass

Screenshots:
skarmavbild 2016-11-03 kl 14 38 27
skarmavbild 2016-11-03 kl 14 38 45

It is this theme:
http://themefeeder.net/themes/wordchef/home/

### CODE REVIEW

**Comment by tochman** [comment]
I would love to see some screenshots

**Review by tochman — APPROVED** [review]
Looks good @thesuss Good job.

**Comment by tochman** [comment]
Posted in Slack by @thesuss 
If anyone is more experienced with haml/partials than myself, feel free to try to help me with the last bits in my WIP-PR

```
- Refactor to link helpers where possible
- Refactor from double quotes and hash-rockets where I have missed (mailers)
- Try to make a partial of the wrap etc before ´%header.entry-header´ (when I try the wrap closes before the ´%header.entry-header´)
```

**Comment by lollypop27** [comment]
@thesuss love the clean look well done!

**Pull request merged**
