### PR TITLE
A complete redesign of the frontend

### PR DESCRIPTION
**Pull request by thesuss**
In order for everyone to feel at home the system should look like the "mother"-site which is wordpress. 
Now the system is using styled bootstrap which will be easier to amend upon changes of the main site. 

I'm sure there are some imperfect details in the design, but as MVP I think it should be fine

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
@thesuss  I did work on the menus so they'll pass Rspec.  I did **not** make the 'knowledgebank link should be blank" pass because it seems that the test is now wrong; it seems that the test _should_ look for a link.

I didn't do any work with the features (out of time for now).

HTH.

**Comment by weedySeaDragon** [comment]
updated code to address the failing features.

**Comment by thesuss** [comment]
I need to amend the menu to match www.sverigeshundforetagare.se anyway, so more tests will fail, but at least now I have info how to fix that, hopefully :)

**Review by weedySeaDragon — CHANGES_REQUESTED** [review]
Here's my feedback after going through all of the view/pages:

### in general
- [x] buttons on the bottom of some pages need to be _buttons_ (set the class)  Probably just make/use one class for those 'bottom buttons'   I've noted the specific pages below
- [x]  Footer: _must_ include a copyright statement and probably 'general' links to the home page, maybe privacy/GDPR etc.


-  (not part of this PR: we should review whether all of those buttons should be shown.  ex:  logged in as a member, on 'edit my company' do we really need to have a "List all companies" button?)

### landing page (as a visitor)

- [x] make the map a little bigger.  Can make the search form a little smaller by making the search boxes a little smaller.  Also: do we really need that text that says "... companies are listed below...?"

landing page - map bigger and zoom in


---
---

### logged in as a *Member*

- [x] **My account** proof of membership buttons ~are in the wrong places.~  Ok. now I see that they are in the right place.  But because of the size of the buttons, it looks awkward to me.  Maybe make the buttons a wee bit shorter so they fit with the flow of the text better?  
This one seems like it might just be _my_ problem.  

my account - proof of members image buttons

---

 - [x] **My Company: Add an address and  Edit address:** bottom button "view" needs to be a button

add address - bottom view button

---

- [ ] **Edit my company** bottom buttons need to be buttons

edit my company - bottom buttons

---

- [ ] **Edit my profile** back button on the bottom needs to be a button

edit my profile - back button


---

- [ ] **View my company** bottom buttons need to be buttons

view my company - bottom buttons edit all


---
---

### logged in as *Admin*
- [ ] **users: change the password for a user**.   bottom "save" buttons needs to be a button:

user-change-pwd-savebutton-1801101320

---

**Comment by thesuss** [comment]
I'll deal with above and then @patmbolger  can have a look around

**Comment by thesuss** [comment]
todo: 
The map should be zoomed in 1 more level. ( = default zoom level)

**Comment by weedySeaDragon** [comment]
re: zoom in the map.  
`app/assets/javascripts/google-maps.js` is where the zoom level is set  (if you want to change it)

**Comment by weedySeaDragon** [comment]
@thesuss @patmbolger   re: **tooltips**  I think I've figured out the problem:

The tooltips are defined in a `span`.  That `span` has to surround (wrap/contain) whatever element you want the tooltip to show for.

Ex:  it should be like this:
```
 %span.glyphicon.glyphicon-info-sign{ title: "#{t('.company_numbers_tooltip')}",
                                         data: {toggle: 'tooltip'} }
      = f.label :company_number, t('shf_applications.show.company_number'), class: 'required'
```
_notice that the `f.label :company_number...` is indented so that it is surrounded by the `span`_

Looks like in most of the code, those 2 lines are in the wrong order (and thus the `span` doesn't contain the `element`)

Also -- the tooltip for switching the language works.  That told me that you have all of the right libraries, etc. loaded.

**Comment by thesuss** [comment]
@weedySeaDragon  I cant search in more than one file at the time in c9, can you do a search/replace of
search for
`%span.glyphicon.glyphicon-info-sign`
replace with; 
`%i.fas.fa-info-circle`

or figure out how it can be replaced with 
`icon('fas', 'info-circle') `
and not break down completely

I could not figure the last one out.

**Pull request closed without merging**
