### PR TITLE
Seed data for dev/staging environment PT #137117589

### PR DESCRIPTION
**Pull request by patmbolger**
PT Story: 
https://www.pivotaltracker.com/story/show/137117589

Changes proposed in this pull request:
1. Add logic to seeds.rb to create data in DB for users, members, membership_applications, business categories and companies. 
2. Added the railroady gem to Gem file
3. Including model and controller diagrams created by railroady

**NOTE** Chore https://www.pivotaltracker.com/story/show/137198137 needs to be completed before merging this PR.

**NOTE** See prior reviewer comments in prior version of this PR (closed without merging): https://github.com/AgileVentures/shf-project/pull/118

Ready for review:
@thesuss 
@weedySeaDragon

### CODE REVIEW

**Comment by thesuss** [comment]
@diraulo  ?

**Comment by diraulo** [comment]
Build settings have been updated to only create the DB and run migrations. I don't think we need to seed the DB in the test environment.

[This line](https://github.com/AgileVentures/shf-project/pull/121/files#diff-f7a25bc30a409fc77050703fc048ca8cR144) in the `seed.rb` file will cause problem if `num_regions == 0`

**Comment by patmbolger** [comment]
@diraulo - yes, the test environment definitely should not need to be seeded.  

Regarding the seed file - we will need to run another rake task *before* running the seed file:
```
rails shf:load_regions db:seed
```
The ```shf:load_regions``` will also be needed for production, which is why it is a separate task as opposed to being in the seeds.rb file.

**Comment by patmbolger** [comment]
I uploaded some changes:
1) Improved messages for logging (in lib/tasks/shf.rake)
2) Changed logic in seeds.rb so that it does not fail if ```num_regions == 0``` (instead, prints message reminding user to use rake task to add regions)

**Review by thesuss — APPROVED** [review]

**Pull request merged**
