### PR TITLE
Generate sitemap

### PR DESCRIPTION
**Pull request by Luleherll**
## Changes proposed in this pull request:
- install sitemap_generator, whenever
- create sitemap

## Ready for review:
@

### CODE REVIEW

**Comment by thesuss** [comment]
Looks good to me, but I'll leave the code-eyes to @weedySeaDragon  =)

**Comment by weedySeaDragon** [comment]
changes to config file:

```
# Set the host name for URL creation
SitemapGenerator::Sitemap.default_host = "https://hitta.sverigeshundforetagare.se"

SitemapGenerator::Sitemap.compress = false

SitemapGenerator::Sitemap.create do

  # Default version (and URLs) is the Swedish (svenska) version:
  group(filename: :svenska) do

    add root_path, changefreq: 'daily', priority: 0.8

    Company.find_each do |co|
      add company_path(co), lastmod: co.updated_at, changefreq: 'weekly'
    end
  end


  # English version:
  # pass in 'locale: :en' to  each path to get the English version
  group(filename: :english) do

    add root_path(locale: :en), changefreq: 'daily', priority: 0.7

    Company.find_each do |co|
      add company_path(co, locale: :en), lastmod: co.updated_at, changefreq: 'weekly'
    end
  end


end

```

**Comment by weedySeaDragon** [comment]
update this section in the .gitignore:

```

# Ignore all logfiles and tempfiles.
logfile
*.log
*.tmp
/log
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

```

**Review by weedySeaDragon — COMMENTED** [review]
great!

**Review by weedySeaDragon — APPROVED** [review]

**Pull request merged**
