### PR TITLE
[WIP] view all companies - pagination intermittent failures

### PR DESCRIPTION
**Pull request by weedySeaDragon**
This is how I've fixed up the _pagination_ scenarios for the **View All Companies** feature.
PT Story: (none)

I kept getting intermittent failures in `cucumber features/view_all_companies.feature:145 # Scenario: Pagination: Set number of items per page`

Here's what the failure looked like:
( I added the line breaks here for readability)

```
expected not to find text "Company26" in "Skip to content LOG IN FIND H-LABELED COMPANIES Map data ©2017 Google Terms of Use Report a map error Map Satellite Member companies are listed below. Search for companies using the search form. 

Show Form 

Category Name Region Municipality
 Company26 Stockholm Alingsås 
Company14 Stockholm Alingsås 
Company16 Stockholm Alingsås 
Company20 Stockholm Alingsås 
Company3 Stockholm Alingsås 
Company5 Stockholm Alingsås 
Company19 Stockholm Alingsås
Company2 Västerbotten Bromölla 
Company9 Stockholm Alingsås 
Company27 Stockholm Alingsås 
Company4 Stockholm Alingsås 
Company8 Stockholm Alingsås 
Company11 Stockholm Alingsås 
Company13 Stockholm Alingsås
 Company17 Stockholm Alingsås 
Company25 Stockholm Alingsås 
Company6 Stockholm Alingsås 
Company23 Stockholm Alingsås 
Company10 Stockholm Alingsås
 Company15 Stockholm Alingsås 
Company21 Stockholm Alingsås 
Company18 Stockholm Alingsås
 Company1 Stockholm Alingsås 
Company22 Stockholm Alingsås 
Company12 Stockholm Alingsås 
« Previous 1 2 Next » 10 25 50 All

 © 2017 Theme by Theme Feeder. All Rights Reserved." 

(RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/assertion_steps.rb:69:in `/^I should( not)? see ((?:t\(".*\)|"[^"]*"))$/'
features/view_all_companies.feature:163:in `And I should not see "Company26"'

Failing Scenarios:
cucumber features/view_all_companies.feature:145 # Scenario: Pagination: Set number of items per page


```

Changes proposed in this pull request:
1.  put the pagination scenarios into their own Feature
2. created additional scenarios so that we exercised each possibility for the # to select (e.g. 10, 25, All)  (Before, we had one long scenario that did each one, but we never exercised just making 1 change -- which, it turns out, caused failures at first)
3. Slowly and painfully figured out the right combination of steps to get them passing reliably  on my machine.

@patmbolger

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
FYI --
I commented out nearly all of the "And I should see "Companyxx" steps and it's still working fine.   (on my dev machine) yay!

**Comment by patmbolger** [comment]
I was getting persistent failures in two scenarios until I added "wait for Ajax ..." after clicking the sort link (which, of course, is also an XHR call).

This what I have now, and both are passing without the superfluous "select 10 items" step:
```
@selenium @time_adjust
  Scenario: view 25 companies; ensure the company name is not shown if it is > items_count selected to show
    Given the date is set to "2017-10-01"
    Given I am Logged out
    And I am on the "landing" page
    Then I should see t("companies.index.h_companies_listed_below")
    And I click on t("toggle.company_search_form.hide")
    And I click on t("activerecord.attributes.company.name") link
    And I wait for all ajax requests to complete
    # Then I select "10" in select list "items_count"
    Then I select "25" in select list "items_count"
    And I wait for all ajax requests to complete
    And "items_count" should have "25" selected
    And I should see "Company01"
    And I should see "Company25"
    And I should not see "Company26"
```

And:

```
@selenium @time_adjust
  Scenario: view all companies
    Given the date is set to "2017-10-01"
    Given I am Logged out
    And I am on the "landing" page
    Then I should see t("companies.index.h_companies_listed_below")
    And I click on t("toggle.company_search_form.hide")
    And I click on t("activerecord.attributes.company.name") link
    And I wait for all ajax requests to complete
    # Then I select "10" in select list "items_count"
    Then I select "All" in select list "items_count"
    And I wait for all ajax requests to complete
    Then I should see "27" companies
    And "items_count" should have "All" selected
    And I should see "Company01"
    And I should see "Company27"
```
The test structure seems to have trouble handling two concurrent XHR calls (or, at least sometimes and on some combination of HW/SW).

**Comment by weedySeaDragon** [comment]
ya -- I wonder how many threads are being created, when and for what.  It smells like asynchronous thread timing stuff for sure.

I'll put in the `wait....` steps as you did and will report back.

**Comment by weedySeaDragon** [comment]
The company features are now working.

But I can't get the  shf_applications pagination scenarios to pass.  <sigh>

thoughts?  See something that I'm missing or doing wrong?

**Comment by patmbolger** [comment]
I haven't been able to get the SHF apps pagination tests to work yet, as well.  Will keep trying.

**Comment by weedySeaDragon** [comment]
FYI, @patmbolger -- I've been working on a PR for "Admin can see all companies (not just complete ones)" and think I've stumbled on a fix.
<sigh>

**Pull request closed without merging**
