### PR TITLE
153361304 - Application edit.

### PR DESCRIPTION
**Pull request by nisevi**
PT Story: https://www.pivotaltracker.com/story/show/153361304

Changes proposed in this pull request:
1. Logic for handling when a file was added or deleted from an application;

### CODE REVIEW

**Comment by nisevi** [comment]
With the changes that I've done this is the error that I'm facing:

```

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) ShfApplication states, events, and transitions actions taken on state transition application rejected need tests here
     # Temporarily skipped with xit
     # ./spec/models/shf_application_spec.rb:341


Failures:

  1) I18n does not have missing keys
     Failure/Error:
       expect(missing_keys).to be_empty,
                               "Missing #{missing_keys.leaves.count} i18n keys, run `i18n-tasks missing' to show them"
     
       Missing 2 i18n keys, run `i18n-tasks missing' to show them
     # ./spec/i18n_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 1 minute 7.86 seconds (files took 3 seconds to load)
1175 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/i18n_spec.rb:9 # I18n does not have missing keys

Coverage report generated for RSpec to /home/runner/shf-project/coverage. 1131 / 1785 LOC (63.36%) covered.
```

**Comment by nisevi** [comment]
Regarding the `Rspec` error I think that is due to the change on the redirections that I've done what is affecting the behavior of our tests, so I will take a look to them to see what is happening :+1:

**Comment by patmbolger** [comment]
@nisevi - that error is due to missing translations - run the command it suggests and it will show you those.

**Comment by nisevi** [comment]
@patmbolger I got the answer :+1: 

```
i18n-tasks missing
warning: parser/current is loading parser/ruby24, which recognizes
warning: 2.4.0-compliant syntax, but you are running 2.4.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Missing translations (1) | i18n-tasks v0.9.18
+--------+------------------------------------+----------------------------------------------------+
| Locale | Key                                | Value in other locales or source                   |
+--------+------------------------------------+----------------------------------------------------+
|  all   | shf_applications.rendering.success | app/controllers/shf_applications_controller.rb:172 |
+--------+------------------------------------+----------------------------------------------------+
```

**Comment by nisevi** [comment]
@patmbolger I added the missing translation, however since I'm not using them, is this way that it should be done? I don't have experience working with `i18n`, so I would like to know a little more how is being used on our project :+1:

**Comment by nisevi** [comment]
I think this one is ready for review @patmbolger @thesuss :+1:

**Review by thesuss — APPROVED** [review]

**Pull request merged**
