### PR TITLE
removes unused social links

### PR DESCRIPTION
**Pull request by lollypop27**
PT Story: https://www.pivotaltracker.com/story/show/149121711
Social media links not correct

Changes proposed in this pull request:
1. Remove Twitter Link
2. Remove Linked In Link
3. Remove YouTube Link

Screenshots (Optional):

Ready for review:
@patmbolger @weedySeaDragon

### CODE REVIEW

**Comment by patmbolger** [comment]
@lollypop27 - what is the (first) line of social media links for?   None of them seem to work ....

screen shot 2017-08-29 at 4 22 11 pm

Perhaps we should get rid of those also?  Then, just add the email link to the same row as the remaining links(?)

**Comment by weedySeaDragon** [comment]
@patmbolger The intent of the "other" links are so that the user (the site visitor/member) can share the links on _their_ FaceBook page or Twitter, etc.  

As I recall, these are in there because this needs to have the same layout as the WordPress pages (the 'other' pages in the site).  Is that right, @thesuss ?

Perhaps we should comment the code to make this clear.  This question/issue has come up repeatedly, which is a signal that the intent is not clear.    This could be done in this or a separate PR.

**Comment by lollypop27** [comment]
@patmbolger the top SM if you click on them share a link of the SHF website to a persons SM page. I wouldn't remove those.
The bottom icons are the issue when you clicked on them they are supposed to take you to SHF social media pages which were not setup as per https://github.com/AgileVentures/shf-project/issues/306

**Review by weedySeaDragon — APPROVED** [review]

**Comment by patmbolger** [comment]
@lollypop27 - do the links work for you?  I seem to have a problem with the FB and Google+ links:

The FB link shows this for me:

screen shot 2017-08-30 at 6 57 47 am

Google+ brings me here but there is no "SHF" indication or message preface:

screen shot 2017-08-30 at 7 01 03 am

Does FB work for you?  Perhaps it is my FB settings.

**Comment by lollypop27** [comment]
@patmbolger I will look into what is happening there

**Comment by lollypop27** [comment]
@patmbolger after doing some research I agree with @weedySeaDragon, that a sperate issue should be created for the Social Media Share buttons/links on the top row and this PR be merged in.

**Pull request merged**
