### PR TITLE
Search for Companies near - Server actions

### PR DESCRIPTION
**Pull request by weedySeaDragon**
### PT Story: server-side logic for searching for a Company by location
https://www.pivotaltracker.com/story/show/161997789

This is just the backend (server side) behavior for searching for Companies given a location name or coordinates (latitude, longitude).

### Changes proposed in this pull request:
1.  added `.company_address` scope to Address
2. added `.at_addresses` scope to Company _(I don't like this name.  Suggestions for a different name?)_
2. added a model responsible for searching for the Companies in the data: CompanyLocator
3. added `.string_sanitizer` to InputSanitizer
4. added logic in `CompaniesController#index` that checks to see if `near:` is in the parameters passed in.  If it is, then we are doing some kind of _search for companies near..._ .  Parse the parameters and do the search.

Ready for review:
@patmbolger

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
whoa.  a RSpec view test is now failing. Looks like perhaps something to do with the `rails-controller-testing` gem.  When I ran all of the rspec tests as a suite I also stupidly was mucking around with other stuff.  So I assumed the failure was my doing.  The view test passes fine when run individually.
<sigh>

I'll investigate.

**Comment by weedySeaDragon** [comment]
@patmbolger Adding the `rails-controller-testing` exposed problems with the view tests.  The gem enforces the convention that the name of the controller and view being tested is taken from the description of the RSpec.  

The view tests should be a feature, IMNSHO, since they do a full integration test of the UI (and then check the source of the view for content in the header).

We can rewrite the tests as features.

**Comment by patmbolger** [comment]
@weedySeaDragon - I wonder why Rails is removing `assigns` from `rspec-rails`?  There must be a reason (" ... but ours is not to reason why .... ").  In any case, you may want to consider using the suggested work-around noted here: https://stackoverflow.com/questions/32635391/accessing-controller-instance-variables-from-within-an-rspec-controller-spec (second answer).

I removed `rails-controller-testing` from the gem file and the `spec/controllers/companies_controller_spec.rb` tests worked when I used that approach.  That is, for instance, changing:
```
expect(assigns(:all_visible_companies).map ....
```
to
```
expect(@controller.view_assigns['all_visible_companies'].map ....
```
Also, most of the view tests conform to that convention you mention.  I'm sure we could get the single failing test to conform - although, if we use the revised approach above, we don't need to.

Also, the view tests that I wrote for testing the menu structure were meant to be fast and lightweight, since I am really only testing the presence of expected menu items.  Doing that with a full-blown cucumber test seems needlessly complex.  Let's discuss at next meeting.

**Comment by weedySeaDragon** [comment]
@patmbolger I  changed the controller spec to use  `@controler.view_assigns[...]` and removed the rails-controller-testing gem.
But the `selective_asset_load_spec.rb`   `is not loaded on other pages` **is still failing.**  Interestingly, it passes when run by itself, but I (finally) found that when it is run with the `model/company_spec.rb`, it fails!
I tagged those 2 specs with `focus: true` so that they can easily be run with `rspec.... --tag focus`

It seems that when RSpec is run, it tries to assign the controller and action using what is in the `describe...` statement.  It seems to have something to do with the fact that more than 1 view is really being called.  First the `company/index` view is called, and within that the `_companies_list` view is rendered -- and that is where the controller and action are derived from the `describe` statement.

Perhaps those tests/specs can be put into their own file and own  top level `describe <controller/view> do...`  spec?

Other than that view spec failing, are things OK?  If so, I'd like to start working on the front end stuff.

**Comment by patmbolger** [comment]
@weedySeaDragon - that is strange that the test started to fail now, and that is it somehow coupled with the Company model tests.

Anyway, I was able to get it to work by adding this line to the `'is not loaded on other pages'` spec:
```
stub_template 'companies/_companies_list' => ''
```
I did not know you could do this (nor that we needed to), but it seems like good practice in any case.  

https://relishapp.com/rspec/rspec-rails/v/3-8/docs/view-specs/stub-template

Probably want to stub `_map_companies` as well ....

**Comment by patmbolger** [comment]
@weedySeaDragon - and yes, I am OK with this WIP PR.

**Comment by weedySeaDragon** [comment]
@patmbolger - If it's ok, can you merge this?  the front end work depends on it and it'd really help to have it merged now that it's updated with the develop branch

**Review by patmbolger — APPROVED** [review]

**Pull request merged**
