### PR TITLE
Routes in swedish

### PR DESCRIPTION
**Pull request by thesuss**
PT Story: https://www.pivotaltracker.com/story/show/133316647
188n translations

Changes proposed in this pull request:
1. Swedify routes 
2. Unit tested new routes

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
We won't be showing different route names based on locale.  (We could, but I'd have to understand why it's valuable do to it.)  So we don't need to do any I18n stuff with it.  (Good instincts, though!)

However we _do_ need some RSpec tests since we're now varying from what Rails normally generates (and thus what has already been validated by umpteen kathousand Rails apps).

I'm sure that your changes will pass just fine. But we want to (1) specify exactly what should be happening, and (2) ensure that if someone comes in and makes a change to this, it will still work reliably.

I'll work on the RSpec tests and will contribute them.

**Comment by thesuss** [comment]
Thanks!

**Review by patmbolger — APPROVED** [review]
PR looks good.

**Comment by patmbolger** [comment]
Note - you should rebase this branch against develop before merging.

**Comment by weedySeaDragon** [comment]
why the rebase, @patmbolger ?  (I never feel like I have a good enough understanding of git. <sigh> )

**Pull request closed without merging**
