### PR TITLE
business category form: fix I18n entries for name and description

### PR DESCRIPTION
**Pull request by weedySeaDragon**
Fix I18n entries for 'Name' and 'Description' on the business category form

PT Story: https://www.pivotaltracker.com/story/show/138311071

In the locale `.yml` files, I was trying to combine 2 references to create one value (trying to make 1 string (value) by concatenating 2 references).  Can't really do that in YML.  So I simplified by just adjusting the entry for the model attribute:  `activerecord.model.business_category.name` = Kategori Namn (or 'Business Category Name' in English).  Same for .... `.description`

Changes proposed in this pull request:
1.  change the .yml locale files
2. update the `business_categories/_form` labels for name and description
3. update the features to use `activerecord.model.business_category.name`

Screenshots (Optional):

**Edit:**
screen shot 2017-02-09 at 9 22 24 am
screen shot 2017-02-09 at 9 23 37 am

Ready for review:
@thesuss

### CODE REVIEW

**Comment by thesuss** [comment]
@weedySeaDragon  Had you had a shorter branchname I woukd have grabbed it and fixed it myself. 
So, in swedish one thing is generally one word, so "Kategorinamn" and "Kategoribeskrivning" or just **"Namn" & "Beskrivning"** as I hope admin knows what they are editing.....

**Comment by weedySeaDragon** [comment]
So @thesuss should I just change the field labels to 'Namn' and 'Beskrivning' ?  Whatever makes you happy, I'll do. :-)

Interesting to know about the 'one word' thing.  German is like that, too.  It's kind of interesting that English isn't more like that, since it has such deep roots in that.  Makes me curious about why English developed into a different style.

**Comment by thesuss** [comment]
Yea, do it 👍

**Comment by weedySeaDragon** [comment]
I updated the screenshots @thesuss  -- see if that looks good to you.

**Comment by thesuss** [comment]
Will merge when I've pushed what's now in develop

**Review by thesuss — APPROVED** [review]

**Pull request merged**
