### PR TITLE
New form landing

### PR DESCRIPTION
**Pull request by thesuss**
from
image

to
image

### CODE REVIEW

**Comment by thesuss** [comment]
I need help with implementing this type of thing in the toggle function: 

```
<button onclick="myFunction()"  id="p2" aria-expanded="false">Try it</button>
<p id="demo"></p> <script>
  function myFunction() {
  var x = document.getElementById("p2").getAttribute("aria-expanded"); 
  if (x == "true") 
  {
  x = "false"
  } else {
  x = "true"
  }
  document.getElementById("p2").setAttribute("aria-expanded", x);
  document.getElementById("p2").innerHTML = "aria-expanded =" + x;
  }
</script> 
```

if the link/headline has `aria-expanded="true"` the arrow changes accordingly

**Comment by thesuss** [comment]
I'd very much like the function/look as in `d4d510c` but with the change of words. I think with team-work we can get there :)

**Comment by thesuss** [comment]
Also I know the rockets: => are outdated but I dont have the brains to make it better :( 
(I use html2haml which provides them)

**Comment by thesuss** [comment]
And I guess a Look n Feel review after that :)

**Comment by weedySeaDragon** [comment]
Fixed the hide/show carat (indicator) not working:  the `Utility.toggle` function we had was 'catching' the click action and adding/removing the `.hide` and `.show` classes.  That interferes  with the jquery hide/collapse actions.
Replaced that with `addEventListener`.

I wasn't able to get the hide/collapse to work vertically.  Interestingly, the hide/collapse for the Admin: Change User's Password _does_ do a vertical hide/collapse. It must be a style thing buried deep down in Bootstrap 4 .  (a .panel vs. button difference?)

**Comment by weedySeaDragon** [comment]
Cucumber tests are failing again when text should not be visible to a user but is present as an option  (e.g. in a drop-down list) -- even when the form with the options is collapsed and not visible.  This seems to be a real difference with how Capybara drivers determine whether or not something is visible to the user and how jquery (maybe javascript?) handles a collapsed element.

Interestingly, they all passed on my local machine.

`<shakes head>`

I know we had some code that addressed this at some point.

**Comment by weedySeaDragon** [comment]
It is really slow getting things to pass when they only fail on Semaphore.  (like back in the _old days_ when it took 20 minutes to compile, link, and load your programs!)

**Comment by weedySeaDragon** [comment]
I wonder if the cucumber tests are failing because we need to wait for the search forms to collapse or expand.
I notice in the failing test that even though the search form should be *hidden,* "Hide the search form" is still being displayed.

@patmbolger @thesuss @rmzse  - are these feature tests passing or failing on your local machines?  Specifically the `search_companies.feature`, and then any of the others that have a hide/show search form on them.

**Comment by thesuss** [comment]
I think you overcomplicated your thinking on this one. 

I'm 90% sure the old toggle function could be expanded with the https://github.com/AgileVentures/shf-project/pull/632#issuecomment-475425818 and all would have been sweet? 

If not I suggest just go back to `d4d510c` fix the one failing test and then use `Show/Hide search form` 

I think maximum 3-4 files should be affected in *this* PR. 
Anything outside of that should be separate issues....

**Comment by weedySeaDragon** [comment]
It's a little bit more complicated -- even if I go back to the `d4d510c` commit.
I have to change the javascript because now we just want to replace the text; we want Bootstrap (and jquery) to handle the show/hide functionality.  And I have to change how that javascript is called (using `addEventListener` instead of binding to `click`)
So that means changes to `application.js`  `utilities.js` and `app/views/companies/index.html.haml` and `app/views/shf_applications/index.html.haml`

In addition:  the show/hide on the `app/views/shf_applications/index.html.haml` was missing the `data-toggle` attribute so it wasn't working.  I added it.

Then: When I change the javascript as needed so that the show/hide works on the companies#index page and the shf_applications#index page, I start to get failing feature tests because capybara checks no longer work with a collapsed form:  Because every individual element in the form is _not_ set to hidden (e.g. `display:none`), we can no longer do a test that says "I should not see <element in the form>"  So we have to change the tests.  (This is a valid change.)
So that means changes to some `feature...` files

There is repetition in the locale files with the 'show/hide/ text, so those need updating: `en.yml` and `sv.yml`  (Best to update small things while you're working on them.  There is definitely a trade-off between making a new story and PR and just updating while you're there.)

I did create the helper method so that all of the attributes would be set automatically for a show/hide element.  And you're right:  _that_ should be a separate PR. :-)

I'll submit some changes based on the `d4d510c` commit in a few minutes.

**Comment by weedySeaDragon** [comment]
annnndd  we're back to failing tests that don't fail on my local machine.

@patmbolger Can you take a stab at this?  Either start over or see if these features pass on your local machine?  (If all tests pass on our local machines but fail here, one thing I'd like to do is set some tags on the AdminDashboard and Conditions features and Semaphore settings so that we can skip those if we want; that will save a lot of time figuring it out.)

**Comment by patmbolger** [comment]
@weedySeaDragon I can take a look this weekend.  Such fun!

**Pull request closed without merging**
