### PR TITLE
Add membership number column to the applications listview

### PR DESCRIPTION
**Pull request by RobertCram**
PT Story: https://www.pivotaltracker.com/story/show/150414246

**Changes proposed in this pull request:**
1. Add a column for the membership number to the applications list (no searching/sorting - that is left for PT https://www.pivotaltracker.com/story/show/150525516)

2. Add a feature test to check for the necessary columns

Ready for review:
@patmbolger @weedySeaDragon @thesuss

### CODE REVIEW

**Review by patmbolger — COMMENTED** [review]
Looks good.  I had a question about the scope of the story - added to PT.

If the answer is "yes", then perhaps the other views could be addressed in this story, or in a separate story.

**Review by weedySeaDragon — APPROVED** [review]
Looks good.  I just have a suggestion:

I'd  _like_ to see the membership_number also be a`link_to`   the membership application, just like the name:  `membership_application_path(membership_application.id)`

This could be a question we can ask the client when it is demo'd.  (I will add this comment in the PT story).

**Review by patmbolger — APPROVED** [review]

**Review by thesuss — CHANGES_REQUESTED** [review]
The headline of the column could/should be a simple "#" or "Nr." so not to take up more space than the numbers themselves. The table looks a bit tilted as is now. 

Other than that it's great. 

It does not need to be a link (in this PR).

**Comment by RobertCram** [comment]
@thesuss: I changed the header to "No." in the English version and to "Nr." in the Swedish one.

**Review by thesuss — APPROVED** [review]

**Pull request merged**
