### PR TITLE
Sender name of emails#154355653

### PR DESCRIPTION
**Pull request by weedySeaDragon**
## PT Story:  #154355653 Send name for emails

finishing #544 ( would need write access to that other repo to push my changes there)

## Changes proposed in this pull request:
1. Use Mail::Address.new and let it automatically format address
2. tiny grammar fix for a test title

Ready for review:
@patmbolger @thesuss

### CODE REVIEW

**Comment by patmbolger** [comment]
@weedySeaDragon I am seeing the reply-to email address twice in my mail client:

screen shot 2018-11-05 at 12 17 05 pm

---

screen shot 2018-11-05 at 12 17 16 pm

**Comment by weedySeaDragon** [comment]
Good catch @patmbolger .  I'll also look at the tests to see if we can catch this kind of error there.

**Comment by weedySeaDragon** [comment]
@patmbolger  see if it's working better now.

**Comment by patmbolger** [comment]
@weedySeaDragon - I'm still seeing a duplicate "reply-to" address.

I also see this in gmail (browser) when I click on "reply":

screen shot 2018-11-06 at 12 55 24 pm

**Comment by weedySeaDragon** [comment]
@patmbolger  what does the email header look like?  That'll help me see exactly what the reply-to field contains.

Never mind.  I see it, too.  There are 2 "reply-to" entries in the header.  

Thanks for helping me see that!

**Review by patmbolger — APPROVED** [review]

**Pull request merged**
