### PR TITLE
Person-Member-Company model (visuals)

### PR DESCRIPTION
**Pull request by weedySeaDragon**
**PT Story:**  
As developers,
we must have a common understanding of what the main 'things' are in the system
and a common vocabulary 
so that we can discuss things effectively
And
we must agree on and define the minimum 'entities' that must be included in MVP1
so that coding can commence!

**Changes proposed in this pull request:**

1.  I created a PDF with a graphic (using Omnigraffle) so that we can discuss, collaborate, percolate, and come to some kind of agreement.  It's _not_ a formal diagram, mostly because I think that's overkill, and also I don't know who knows which notation(s).

2. I put the documents (PDF + graphic source file) in github so that we can track and talk about revisions even if we're not connected.  I think this is really important at the beginning, when we have to come to a point where we have a common concept *and* come to some agreement on it.

3. I created the **docs** directory and put them in there.  

**Here's a png version if you don't want to or can't deal with the PDF:**

shf-major-parts--v01-thumbnail

Ready for review:
@thesuss @lollypop27 @tochman

### CODE REVIEW

**Comment by weedySeaDragon** [comment]
Already I see some issues to discuss:
1. **DinKurs** is the _Events_ system, yes?  So that needs to be change _and_ we need an 'external system' box to represent the _officially recognized / stamped_ data that we get from elsewhere (spreadsheet?)
2.  There should be an arrow between **Membership** and **uploaded file** that shows _a Membership has 0..many uploaded files_
3.  Perhaps _Membership_ should be called **"Membership Info"** ?  It seems clearer to me (less abstract).

**Comment by thesuss** [comment]
Din kurs is **an** events system used by many of the members. Has discounts for our members. 

I think this is spot on, am venting it with the people of the association, will see if they have any comments.

**Comment by thesuss** [comment]
Chairman of the board put her stamp of approval on this concept. And I think that if we can make this happen it would be so very awesome!

**Review by thesuss — APPROVED** [review]

**Comment by weedySeaDragon** [comment]
Based on conversation with @thesuss  on Slack:  there is **no external system** that keeps track of who is _'officially recognized / stamped '._  SHF owns that info; it's not currently part of their system.  (So there will need to be a way to import that data, initially.)   

That was just my confusion.  I'll update the graphic to reflect that.

**Comment by weedySeaDragon** [comment]
**I've revised the graphic.** DinKurs is now corrected to show it's an event system.

  Here's the current version:

shf-major-parts--v02

**Comment by weedySeaDragon** [comment]
Here's a _very simple_ flow of what happens when a Visitor applies for a company membership.

Please see the Epic _"[Visitor (not logged in) submits a CompanyMembership Application](https://www.pivotaltracker.com/epic/show/3131853)"_ in Pivotal Tracker that @thesuss  and I created at the end of today's scrum.

I put 'company' in here just to be sure to convey that the information about a company from _the application_ will not be lost.   Initially (for MVP1), _Company_ may or may not be the same 'thing' as a CompanyMembership.

shf-major-parts--v02-app

**Pull request merged**
