### PR TITLE
qualification process diagrams: v1 and v2

### PR DESCRIPTION
**Pull request by weedySeaDragon**
## Changes proposed in this pull request:
1. added a digram  showing version 1 of the qualification process: any document uploaded makes the applicant qualified
2. added a diagram showing version 2 of the qualification process: an admin must review 'qualification documents' that have been uploaded.

## Notes:

- version 2:  The process flow is simplified:  I did not show that there is a loop for an admin reviewing all documents until there are no more to review. When this diagram is reviewed and OK'd, we can define the process in more detail.

- I have not done version 3 (applicant has a time limit for uploading documentation showing their qualifications) yet.  I want to get feedback on these 2 diagrams first.

You might need to _view_ the files to see the diagrams

Ready for review:
@thesuss 
@patmbolger

### CODE REVIEW

**Comment by patmbolger** [comment]
@weedySeaDragon I wonder if it would be better to not show the payment button until the terms acceptance (code of ethics) has been checked (or show the payment button but as disabled / greyed out, with a popup explaining that the terms have to be accepted first).

We should also note somewhere that the current de-membership process has to be enhanced to auto "uncheck" the terms acceptance under membership expiration.

**Comment by weedySeaDragon** [comment]
@patmbolger @thesuss  I've updated the diagram for version 1:  

Feedback?

(I also uploaded a .PDF version of the diagram just in case it's helpful for the SHF meeting, Susanna.)

**Comment by patmbolger** [comment]
@weedySeaDragon - this revision looks good.  More detail can be flushed out when we actually implement it.

**Comment by thesuss** [comment]
I went here on the meeting and they agree this is a good process. 
Though currently it would go against the bylaws ro implement, or at least to make it mandatory. 
So we probably need to wait til march to actually do it. I'm afraid. We'll see.

**Comment by weedySeaDragon** [comment]
@thesuss no worries.  It happens.  At least now you'll be ready for March and the board will be a little bit familiar with this when it's time to revisit it.

**Review by patmbolger — APPROVED** [review]

**Pull request merged**
