### PR TITLE
Fixes many details on the user view

### PR DESCRIPTION
**Pull request by thesuss**
as admin: 
Old - New
image

as user: 
image

### CODE REVIEW

**Comment by patmbolger** [comment]
I know the emphasis has been on user-visible items and not admin views.  However, the applications admin view looks great except that the "hide search form" is barely visible:

Screen Shot 2019-03-30 at 2 40 38 PM

And when hidden the "show" version is invisible except for a border:

Screen Shot 2019-03-30 at 2 42 39 PM

**Review by patmbolger — APPROVED** [review]
Looks much better pretty much everywhere.

See one comment re admin apps mgmt view - can be separate story if desired.

**Comment by weedySeaDragon** [comment]
Agree with @patmbolger  -- much better!  
I made a new PT story for the **Admin: manage SHF Application page: show/hide search button**
https://www.pivotaltracker.com/story/show/165003584

(I put it into a random place the backlog.  Don't know what the priority should be.)

**Comment by thesuss** [comment]
"And when hidden the "show" version is invisible except for a border:" it doesnt if you click outside it tho.

**Pull request merged**
