### PR TITLE
set default from, reply-to and display name

### PR DESCRIPTION
**Pull request by tomurb**
PT Story: 

Changes proposed in this pull request:
1. default display name set to "Sveriges Hundföretagare"
2. default From: address set to info@sverigeshundforetagare.se
3. default Reply-to: address set to medlem@sverigeshundforetagare.

Ready for review:
@AgileVentures/shf-project-team

### CODE REVIEW

**Comment by tomurb** [comment]
I guess specs fail because I've changed the .env.
Here are lines 45-47
```SHF_SENDER_EMAIL=noreply@sverigeshundforetagare.se
SHF_EMAIL_DISPLAY_NAME='Sveriges Hundföretagare' 
SHF_FROM_EMAIL='info@sverigeshundforetagare.se'
SHF_REPLY_TO_EMAIL='medlem@sverigeshundforetagare.se'
```

I deleted `SHF_NOREPLY_EMAIL` and `SHF_MEMBERSHIP_EMAIL`.

**Comment by patmbolger** [comment]
I still see SHF_NOREPLY_EMAIL being used:

screen shot 2018-07-09 at 8 22 06 am

---

Also, SHF_MEMBERSHIP_EMAIL:

screen shot 2018-07-09 at 8 22 57 am

**Comment by patmbolger** [comment]
Please add the new ENV vars to `env.example`.  Also, remove any that you've replaced.

**Comment by patmbolger** [comment]
I added the 3 new ENV vars to the project setup on semaphoric (and am running the tests again as I write this).

I did not remove the 2 deleted ENV vars (from your note above) because of existing references still in the code.

**Comment by patmbolger** [comment]
It looks like all of your tests are running OK.  The cucumber failures (3) in semaphoreci are due to the fact that the events for our "test" dinkurs company keeps changing on us (I created this story: https://www.pivotaltracker.com/story/show/158908189).

**Review by patmbolger — APPROVED** [review]

**Pull request closed without merging**
